# This file was generated by GoReleaser. DO NOT EDIT.
class Tog < Formula
  desc "Tog CLI"
  homepage "https://github.com/escaletech/tog-cli"
  version "0.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/escaletech/tog-cli/releases/download/v0.3.1/tog_0.3.1_macOS_amd64.tar.gz"
    sha256 "aa88701e1c1eacd3f3c9cbcba6e37df68b08d8808f8b70464c475c87ffbfd3df"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/escaletech/tog-cli/releases/download/v0.3.1/tog_0.3.1_linux_amd64.tar.gz"
      sha256 "b66db0e0fb22dfb6e6c06286612ac34bc29752770ab4161ecc65e52824525ae6"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/escaletech/tog-cli/releases/download/v0.3.1/tog_0.3.1_linux_arm64.tar.gz"
        sha256 "b45522f47f73d122d2def8103395cd1913235c0b1a3bba431ba40f94d552e75e"
      else
      end
    end
  end

  def install
    bin.install "bin/tog"
  end

  test do
    help_text = shell_output("#{bin}/tog --help")
    assert_includes help_text, "Usage:"
  end
end
